language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
script: make travis
sudo: false
matrix:
    fast_finish: true
    allow_failures:
        - php: 5.3
        - php: 5.4
        - php: hhvm
        - php: nightly
after_script:
  - php vendor/bin/coveralls
